# Generated by Django 6.0.3 on 2026-03-31 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0003_historicalperson_conjoint_nom_libre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('naissance', 'Naissance'), ('deces', 'Deces'), ('mariage', 'Mariage'), ('bapteme', 'Bapteme / Ceremonie'), ('diplome', 'Diplome / Reussite'), ('deuil', 'Deuil'), ('fete', 'Fete'), ('communaute', 'Communaute'), ('autre', 'Autre')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_evenement', models.DateField()),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('est_public', models.BooleanField(default=True, help_text="Visible sur la page d'accueil apres validation admin.")),
                ('statut_validation', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Refuse')], db_index=True, default='pending', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='person.person')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
                'ordering': ['-date_evenement', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_lue', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_evenements', to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
