# Generated by Django 6.0.3 on 2026-03-31 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resume',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='villages.village'),
        ),
    ]
