# Generated by Django 6.0.3 on 2026-03-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_resume_event_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='nom_contact',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='event',
            name='telephone_contact',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
