from django.urls import path
from Apps.blog.views import (
    BlogDashboardView,
    ArticleListAdminView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticlePublierView,
    CommentaireListView,
    CommentaireApprouverView,
    CommentaireRejeterView,
    NewsletterListView,
    CategorieListView,
    CategorieCreateView,
    CategorieUpdateView,
    CategorieDeleteView,
    TagListView,
    TagCreateView,
    TagDeleteView,
)

urlpatterns = [
    path("blog/", BlogDashboardView.as_view(), name="blog-dashboard"),
    path("blog/articles/", ArticleListAdminView.as_view(), name="blog-article-list"),
    path("blog/articles/creer/", ArticleCreateView.as_view(), name="blog-article-create"),
    path("blog/articles/<uuid:pk>/modifier/", ArticleUpdateView.as_view(), name="blog-article-update"),
    path("blog/articles/<uuid:pk>/supprimer/", ArticleDeleteView.as_view(), name="blog-article-delete"),
    path("blog/articles/<uuid:pk>/publier/", ArticlePublierView.as_view(), name="blog-article-publier"),
    path("blog/commentaires/", CommentaireListView.as_view(), name="blog-commentaire-list"),
    path("blog/commentaires/<uuid:pk>/approuver/", CommentaireApprouverView.as_view(), name="blog-commentaire-approuver"),
    path("blog/commentaires/<uuid:pk>/rejeter/", CommentaireRejeterView.as_view(), name="blog-commentaire-rejeter"),
    path("blog/newsletter/", NewsletterListView.as_view(), name="blog-newsletter-list"),
    path("blog/categories/", CategorieListView.as_view(), name="blog-categorie-list"),
    path("blog/categories/creer/", CategorieCreateView.as_view(), name="blog-categorie-create"),
    path("blog/categories/<uuid:pk>/modifier/", CategorieUpdateView.as_view(), name="blog-categorie-update"),
    path("blog/categories/<uuid:pk>/supprimer/", CategorieDeleteView.as_view(), name="blog-categorie-delete"),
    path("blog/tags/", TagListView.as_view(), name="blog-tag-list"),
    path("blog/tags/creer/", TagCreateView.as_view(), name="blog-tag-create"),
    path("blog/tags/<uuid:pk>/supprimer/", TagDeleteView.as_view(), name="blog-tag-delete"),
]
