# Generated by Django 6.0.3 on 2026-04-20 10:49

import Apps.cotisations.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_family_created_by_historicalfamily_created_by'),
        ('person', '0006_historicalperson_created_by_person_created_by'),
        ('villages', '0002_village_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptePaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('moov', 'Moov'), ('mtn', 'MTN'), ('virement', 'Virement'), ('espece', 'Espece')], max_length=20, verbose_name='Mode de paiement')),
                ('numero', models.CharField(max_length=100, verbose_name='Numero / reference')),
                ('nom_titulaire', models.CharField(max_length=160, verbose_name='Nom du titulaire')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=Apps.cotisations.models.upload_qr_code, verbose_name='QR code')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='Instructions')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compte de paiement',
                'verbose_name_plural': 'Comptes de paiement',
                'ordering': ['ordre_affichage', 'mode', 'nom_titulaire'],
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Fevrier'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Aout'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Decembre')])),
                ('annee', models.PositiveIntegerField(db_index=True)),
                ('description', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermee')], db_index=True, default='ouverte', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='families.family')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='villages.village')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-annee', '-mois', 'village__nom', 'famille__nom_famille'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('moov', 'Moov'), ('mtn', 'MTN'), ('virement', 'Virement'), ('espece', 'Espece')], max_length=20, verbose_name='Mode de paiement')),
                ('reference_transaction', models.CharField(blank=True, default='', max_length=120, verbose_name='Reference de transaction')),
                ('recu', models.ImageField(blank=True, null=True, upload_to=Apps.cotisations.models.upload_receipt, verbose_name='Recu')),
                ('statut_validation', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Valide'), ('rejected', 'Refuse')], db_index=True, default='approved', max_length=20, verbose_name='Statut de validation')),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='cotisations.comptepaiement', verbose_name='Compte de destination')),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='cotisations.cotisation', verbose_name='Cotisation')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistre par')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_cotisation', to='person.person', verbose_name='Personne')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_cotisation_valides', to=settings.AUTH_USER_MODEL, verbose_name='Valide par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['annee', 'mois'], name='idx_cotisation_periode'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['statut'], name='idx_cotisation_statut'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['personne', 'cotisation'], name='idx_paiement_scope'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut_validation'], name='idx_paiement_validation'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['mode_paiement'], name='idx_paiement_mode'),
        ),
    ]
