# Generated by Django 6.0.3 on 2026-04-20 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_person_tracking_from_payments(apps, schema_editor):
    CotisationPersonne = apps.get_model('cotisations', 'CotisationPersonne')
    Paiement = apps.get_model('cotisations', 'Paiement')

    seen = set()
    for cotisation_id, personne_id in Paiement.objects.values_list(
        'cotisation_id',
        'personne_id',
    ).distinct():
        if (cotisation_id, personne_id) in seen:
            continue
        seen.add((cotisation_id, personne_id))
        CotisationPersonne.objects.get_or_create(
            cotisation_id=cotisation_id,
            personne_id=personne_id,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0001_initial'),
        ('person', '0006_historicalperson_created_by_person_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotisationPersonne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_attendu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant attendu')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_personnes', to='cotisations.cotisation', verbose_name='Cotisation')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_cotisation', to='person.person', verbose_name='Personne')),
            ],
            options={
                'verbose_name': 'Suivi de cotisation par personne',
                'verbose_name_plural': 'Suivis de cotisation par personne',
                'ordering': ['-cotisation__annee', '-cotisation__mois', 'personne__prenom', 'personne__nom'],
                'indexes': [models.Index(fields=['cotisation', 'personne'], name='idx_suivi_scope'), models.Index(fields=['personne'], name='idx_suivi_personne')],
                'constraints': [models.UniqueConstraint(fields=('cotisation', 'personne'), name='uq_cotisation_personne_suivi')],
            },
        ),
        migrations.RunPython(
            populate_person_tracking_from_payments,
            reverse_code=noop_reverse,
        ),
    ]
