# Generated by Django 6.0.3 on 2026-04-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0002_cotisationpersonne'),
        ('families', '0002_family_created_by_historicalfamily_created_by'),
        ('villages', '0002_village_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='est_generale',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cotisation generale'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['est_generale'], name='idx_cotisation_general'),
        ),
    ]
