# Generated by Django 6.0.3 on 2026-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0003_cotisation_est_generale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='email_soumetteur',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email du soumetteur'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='est_soumission_publique',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soumission publique'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='nom_soumetteur',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Nom du soumetteur'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='telephone_soumetteur',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telephone du soumetteur'),
        ),
    ]
