# Generated by Django 6.0.3 on 2026-04-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalutilisateur',
            name='google_auth_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='google_auth_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
