# Generated by Django 6.0.3 on 2026-03-26 12:09

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFamily',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identifiant unique')),
                ('nom_famille', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='villages.village', verbose_name='Village')),
            ],
            options={
                'verbose_name': 'historical Famille',
                'verbose_name_plural': 'historical Familles',
                'db_table': 'families_family_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('nom_famille', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='villages.village', verbose_name='Village')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['nom_famille'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('nom_famille', 'village'), name='uq_famille_village_actif')],
            },
        ),
    ]
