# Generated by Django 6.0.3 on 2026-04-14 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='Nom utilisateur')),
                ('user_role', models.CharField(blank=True, max_length=64, verbose_name='Fonction utilisateur')),
                ('fonction', models.CharField(max_length=255, verbose_name='Fonction')),
                ('action', models.CharField(max_length=120, verbose_name='Action')),
                ('methode', models.CharField(blank=True, max_length=16, verbose_name='Méthode HTTP')),
                ('chemin', models.CharField(blank=True, max_length=500, verbose_name='Chemin')),
                ('statut_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Code statut')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='Adresse IP')),
                ('pays', models.CharField(blank=True, default='Inconnu', max_length=120)),
                ('ville', models.CharField(blank=True, default='Inconnu', max_length=120)),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_histories', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': "Historiques d'actions",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['-date_action'], name='hist_action_date_idx'), models.Index(fields=['action'], name='hist_action_label_idx'), models.Index(fields=['fonction'], name='hist_action_view_idx')],
            },
        ),
    ]
