# Generated by Django 6.0.3 on 2026-05-22 15:09

import Apps.blog.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#00613a', max_length=7, verbose_name='Couleur hex')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie blog',
                'verbose_name_plural': 'Catégories blog',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('confirme', models.BooleanField(default=True, verbose_name='Confirmé')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Slug')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug URL')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to=Apps.blog.models._upload_couverture, verbose_name='Image de couverture')),
                ('extrait', models.TextField(blank=True, help_text='Résumé court affiché dans la liste (max 500 caractères). Généré automatiquement si vide.', max_length=500, verbose_name='Extrait / Résumé')),
                ('contenu', models.TextField(verbose_name="Contenu de l'article")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('planifie', 'Planifié'), ('archive', 'Archivé')], db_index=True, default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_publication', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de publication')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('featured', models.BooleanField(default=False, verbose_name='Article mis en avant')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta titre SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description SEO')),
                ('og_image', models.ImageField(blank=True, help_text='Image pour le partage sur les réseaux sociaux (1200×630 recommandé)', null=True, upload_to=Apps.blog.models._upload_og_image, verbose_name='Image Open Graph')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_blog', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.categorie', verbose_name='Catégorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auteur_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom (visiteur)')),
                ('auteur_email', models.EmailField(blank=True, max_length=254, verbose_name='Email (visiteur)')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='blog.article', verbose_name='Article')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_blog', to=settings.AUTH_USER_MODEL, verbose_name='Auteur (membre)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='blog.commentaire', verbose_name='Réponse à')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=280, verbose_name='Slug URL')),
                ('image_couverture', models.TextField(blank=True, max_length=100, null=True, verbose_name='Image de couverture')),
                ('extrait', models.TextField(blank=True, help_text='Résumé court affiché dans la liste (max 500 caractères). Généré automatiquement si vide.', max_length=500, verbose_name='Extrait / Résumé')),
                ('contenu', models.TextField(verbose_name="Contenu de l'article")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('planifie', 'Planifié'), ('archive', 'Archivé')], db_index=True, default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_publication', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de publication')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('featured', models.BooleanField(default=False, verbose_name='Article mis en avant')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta titre SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description SEO')),
                ('og_image', models.TextField(blank=True, help_text='Image pour le partage sur les réseaux sociaux (1200×630 recommandé)', max_length=100, null=True, verbose_name='Image Open Graph')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('auteur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.categorie', verbose_name='Catégorie')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Article',
                'verbose_name_plural': 'historical Articles',
                'db_table': 'blog_article_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article', verbose_name='Article')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_blog', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('article', 'utilisateur')},
            },
        ),
    ]
