# Generated by Django 6.0.3 on 2026-05-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug URL'),
        ),
    ]
