"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from django.contrib.messages import constants as messages
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from datetime import timedelta
from django.utils.translation import gettext_lazy as _
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j!(0=e3a$gb1v--&)raxvg$0*t+=bxa$ti&r^z4kwb$_!ml2^)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

def _env_list(name: str) -> list[str]:
    raw_value = os.getenv(name, "")
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def _hostname_from_url(value: str) -> str:
    parsed = urlparse(value if "://" in value else f"https://{value}")
    return parsed.netloc or parsed.path


def _origin_from_url(value: str) -> str:
    parsed = urlparse(value if "://" in value else f"https://{value}")
    scheme = parsed.scheme or "https"
    host = parsed.netloc or parsed.path
    return f"{scheme}://{host}"


shared_urls = _env_list("SHARED_BASE_URLS") or [
    "https://ou3rxeus2icl.share.zrok.io",
]

ALLOWED_HOSTS = list(dict.fromkeys([
    "*",
    "localhost",
    "127.0.0.1",
    ".share.zrok.io",
    *[_hostname_from_url(url) for url in shared_urls],
]))


CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://*.share.zrok.io",
    *[_origin_from_url(url) for url in shared_urls],
    *_env_list("CSRF_EXTRA_TRUSTED_ORIGINS"),
]))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',

    #LOCAL APPS
    'Apps.accounts',
    'Apps.diaspora',
    'Apps.families',
    'Apps.villages',
	    'Apps.website',
	    'Apps.dashbord',
	    'Apps.person',
	    'Apps.events',
	    'Apps.cotisations',
	    'Apps.histoire',
    'Apps.medias',
    'Apps.blog',

     # Applications tierces
    'crispy_bootstrap5',
    'crispy_forms',
    'safedelete',
    'corsheaders',
    'simple_history',
    'widget_tweaks',
    "colorfield",
]

AUTH_USER_MODEL = 'accounts.Utilisateur'

AUTHENTICATION_BACKENDS = [
    'Apps.accounts.authentication.EmailOrUsernameModelBackend',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'Apps.histoire.middleware.ActionHistoryMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'Apps/accounts/templates'),
            os.path.join(BASE_DIR, 'Apps/diaspora/templates'),
            os.path.join(BASE_DIR, 'Apps/families/templates'),
            os.path.join(BASE_DIR, 'Apps/villages/templates'),
            os.path.join(BASE_DIR, 'Apps/website/templates'),
            os.path.join(BASE_DIR, 'Apps/dashbord/templates'),
            os.path.join(BASE_DIR, 'Apps/medias/templates'),
            os.path.join(BASE_DIR, 'Apps/blog/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Apps.dashbord.context_processors.admin_navigation_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database loacal

# DATABASES = {

#     'default': {

#         'ENGINE': 'django.db.backends.postgresql',

#         'NAME': 'Olodio',

#         'USER': 'postgres',

#         'PASSWORD': '1234',

#         'HOST': 'localhost',  # Essayez 'localhost' au lieu de '127.0.0.1'

#         'PORT': '5432',

#         'OPTIONS': {

#             'client_encoding': 'UTF8',

#         },

#     }
# }

#Database production

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql',

        'NAME': 'c2805526c_tepov1',

        'USER': 'c2805526c_admin',

        'PASSWORD': '.(6Ty~i)^dGM,HF@',

        'HOST': 'localhost',  # Essayez 'localhost' au lieu de '127.0.0.1'

        'PORT': '5432',

        'OPTIONS': {

            'client_encoding': 'UTF8',

        },

    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr'
LANGUAGES = [
    ('fr', _('francais')),
    ('en', _('English')),
 ]



LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Configuration des fichiers statiques
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Dossiers où Django va chercher les fichiers statiques
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Configuration pour les médias (fichiers uploadés par les utilisateurs)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration WhiteNoise — stockage des fichiers statiques
# WhiteNoise : compression des fichiers statiques (gzip/brotli)
# CompressedStaticFilesStorage = compression sans hash de noms — compatible partout
# Pour un hash des noms (cache long terme), utiliser CompressedManifestStaticFilesStorage
# mais nécessite collectstatic sans fichiers verrouillés.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

if DEBUG:
    WHITENOISE_USE_FINDERS = True  # Sert depuis STATICFILES_DIRS, pas besoin de collectstatic

WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True

# Configuration de Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

 


# smtp
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'empotageoilsofafrica@gmail.com'  # Replace with your Gmail address
EMAIL_HOST_PASSWORD = 'vlym rhmk nmht rhge'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
SUPPORT_EMAIL = 'contact@olodio-pref.ci'

# Authentication settings
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashbord:admin_dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

SITE_NAME = 'Olodio Platform'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SITE_ID = 1

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django.core.mail': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
