# Generated by Django 6.0.3 on 2026-05-22 14:14

import Apps.medias.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie média',
                'verbose_name_plural': 'Catégories médias',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMedia',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identifiant')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], db_index=True, max_length=10, verbose_name='Type')),
                ('fichier', models.TextField(max_length=100, verbose_name='Fichier')),
                ('miniature', models.TextField(blank=True, help_text='Vignette pour les vidéos (optionnel)', max_length=100, verbose_name='Miniature')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('taille_fichier', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('largeur', models.IntegerField(blank=True, null=True, verbose_name='Largeur (px)')),
                ('hauteur', models.IntegerField(blank=True, null=True, verbose_name='Hauteur (px)')),
                ('duree', models.IntegerField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('format_fichier', models.CharField(blank=True, max_length=20, verbose_name='Format')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name="Date d'ajout")),
                ('date_maj', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categorie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='medias.categoriemedia', verbose_name='Catégorie')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploade_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'historical Média',
                'verbose_name_plural': 'historical Médias',
                'db_table': 'medias_media_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], db_index=True, max_length=10, verbose_name='Type')),
                ('fichier', models.FileField(upload_to=Apps.medias.models._upload_to_media, verbose_name='Fichier')),
                ('miniature', models.ImageField(blank=True, help_text='Vignette pour les vidéos (optionnel)', upload_to=Apps.medias.models._upload_to_miniature, verbose_name='Miniature')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('taille_fichier', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('largeur', models.IntegerField(blank=True, null=True, verbose_name='Largeur (px)')),
                ('hauteur', models.IntegerField(blank=True, null=True, verbose_name='Hauteur (px)')),
                ('duree', models.IntegerField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('format_fichier', models.CharField(blank=True, max_length=20, verbose_name='Format')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='medias.categoriemedia', verbose_name='Catégorie')),
                ('uploade_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias_uploades', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['-date_creation'],
            },
        ),
    ]
