# Generated by Django 6.0.3 on 2026-04-15 17:29

import Apps.website.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_family_created_by_historicalfamily_created_by'),
        ('person', '0006_historicalperson_created_by_person_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPersonSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('surnom', models.CharField(blank=True, default='', max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, default='', max_length=200)),
                ('nationalite', models.CharField(default='Ivoirienne', max_length=100)),
                ('numero_cni', models.CharField(blank=True, default='', max_length=50)),
                ('profession', models.CharField(blank=True, default='', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Apps.website.models.upload_to_public_person_submission)),
                ('situation_matrimoniale', models.CharField(choices=[('celibataire', 'Celibataire'), ('marie', 'Marie(e)'), ('divorce', 'Divorce(e)'), ('veuf', 'Veuf / Veuve')], default='celibataire', max_length=20)),
                ('est_vivant', models.BooleanField(default=True)),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('type_residence', models.CharField(choices=[('village', 'Reside au village'), ('ci', "Cote d'Ivoire (hors village)"), ('diaspora', 'Diaspora (hors CI)'), ('inconnu', 'Inconnu')], default='village', max_length=20)),
                ('lieu_residence', models.CharField(blank=True, default='', max_length=200)),
                ('pere_nom_libre', models.CharField(blank=True, default='', max_length=200)),
                ('mere_nom_libre', models.CharField(blank=True, default='', max_length=200)),
                ('conjoint_nom_libre', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('statut_validation', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvee'), ('rejected', 'Refusee')], db_index=True, default='pending', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('conjoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_submissions_as_spouse', to='person.person')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_person_submissions', to='families.family')),
                ('mere', models.ForeignKey(blank=True, limit_choices_to={'genre': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_submissions_as_mother', to='person.person')),
                ('pere', models.ForeignKey(blank=True, limit_choices_to={'genre': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_submissions_as_father', to='person.person')),
                ('personne_creee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_submission_sources', to='person.person')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_person_submissions_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-inscription publique',
                'verbose_name_plural': 'Pre-inscriptions publiques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
