# Generated by Django 6.0.3 on 2026-04-21 12:09

import Apps.website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccueilImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('about', 'A propos')], db_index=True, default='hero', max_length=20)),
                ('titre', models.CharField(blank=True, default='', max_length=200)),
                ('sous_titre', models.CharField(blank=True, default='', max_length=255)),
                ('texte_alt', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Apps.website.models.upload_to_accueil_image)),
                ('image_url', models.URLField(blank=True, default='')),
                ('ordre', models.PositiveIntegerField(db_index=True, default=0)),
                ('est_active', models.BooleanField(db_index=True, default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Image d'accueil",
                'verbose_name_plural': "Images d'accueil",
                'ordering': ['section', 'ordre', '-date_creation'],
            },
        ),
    ]
