# Generated by Django 6.0.3 on 2026-03-26 14:38

import Apps.person.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('surnom', models.CharField(blank=True, default='', max_length=100, verbose_name='Surnom')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(default='Ivoirienne', max_length=100, verbose_name='Nationalité')),
                ('numero_cni', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro CNI')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Apps.person.models.upload_photo_personne, verbose_name='Photo')),
                ('situation_matrimoniale', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf / Veuve')], default='celibataire', max_length=20, verbose_name='Situation matrimoniale')),
                ('est_vivant', models.BooleanField(default=True, verbose_name='Est vivant(e)')),
                ('date_deces', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('type_residence', models.CharField(choices=[('village', 'Réside au village'), ('ci', "Côte d'Ivoire (hors village)"), ('diaspora', 'Diaspora (hors CI)'), ('inconnu', 'Inconnu')], default='village', max_length=20, verbose_name='Type de résidence')),
                ('lieu_residence', models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu de résidence actuel')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('conjoint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjoint_de', to='person.person', verbose_name='Conjoint(e)')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='families.family', verbose_name='Famille')),
                ('mere', models.ForeignKey(blank=True, limit_choices_to={'genre': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_mere', to='person.person', verbose_name='Mère')),
                ('pere', models.ForeignKey(blank=True, limit_choices_to={'genre': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_pere', to='person.person', verbose_name='Père')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('surnom', models.CharField(blank=True, default='', max_length=100, verbose_name='Surnom')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(default='Ivoirienne', max_length=100, verbose_name='Nationalité')),
                ('numero_cni', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro CNI')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Photo')),
                ('situation_matrimoniale', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf / Veuve')], default='celibataire', max_length=20, verbose_name='Situation matrimoniale')),
                ('est_vivant', models.BooleanField(default=True, verbose_name='Est vivant(e)')),
                ('date_deces', models.DateField(blank=True, null=True, verbose_name='Date de décès')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('type_residence', models.CharField(choices=[('village', 'Réside au village'), ('ci', "Côte d'Ivoire (hors village)"), ('diaspora', 'Diaspora (hors CI)'), ('inconnu', 'Inconnu')], default='village', max_length=20, verbose_name='Type de résidence')),
                ('lieu_residence', models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu de résidence actuel')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière modification')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('famille', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='families.family', verbose_name='Famille')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conjoint', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='person.person', verbose_name='Conjoint(e)')),
                ('mere', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'genre': 'F'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='person.person', verbose_name='Mère')),
                ('pere', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'genre': 'M'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='person.person', verbose_name='Père')),
            ],
            options={
                'verbose_name': 'historical Personne',
                'verbose_name_plural': 'historical Personnes',
                'db_table': 'families_person_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['nom'], name='idx_person_nom'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['prenom'], name='idx_person_prenom'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['famille'], name='idx_person_famille'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['pere'], name='idx_person_pere'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['mere'], name='idx_person_mere'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['est_vivant'], name='idx_person_vivant'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['type_residence'], name='idx_person_residence'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['genre'], name='idx_person_genre'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['nom', 'prenom'], name='idx_person_nom_prenom'),
        ),
    ]
