# Generated by Django 6.0.3 on 2026-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='conjoint_nom_libre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom libre du conjoint'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='mere_nom_libre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom libre de la mère'),
        ),
        migrations.AddField(
            model_name='person',
            name='conjoint_nom_libre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom libre du conjoint'),
        ),
        migrations.AddField(
            model_name='person',
            name='mere_nom_libre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom libre de la mère'),
        ),
    ]
