# Generated by Django 6.0.3 on 2026-04-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_historicalperson_conjoint_nom_libre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='pere_nom_libre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom libre du pÃ¨re'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='person',
            name='pere_nom_libre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom libre du pÃ¨re'),
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Profession'),
        ),
    ]
