# Generated by Django 6.0.3 on 2026-03-21 05:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: school, hospital)", max_length=50)),
            ],
            options={
                'verbose_name': "Type d'infrastructure",
                'verbose_name_plural': "Types d'infrastructures",
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('population_estimee', models.IntegerField(default=0)),
                ('chef_village', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('type_infrastructure', models.CharField(choices=[('ecole', 'École'), ('hopital', 'Hôpital'), ('dispensaire', 'Dispensaire'), ('marche', 'Marché'), ('centre_sante', 'Centre de santé'), ('ecole_maternelle', 'École maternelle'), ('lycee', 'Lycée'), ('universite', 'Université'), ('poste_police', 'Poste de police'), ('mairie', 'Mairie'), ('place_publique', 'Place publique'), ('centre_communautaire', 'Centre communautaire'), ('puit', 'Puits'), ('forage', 'Forage'), ('electricite', 'Électricité'), ('telephone', 'Téléphonie'), ('internet', 'Internet'), ('autre', 'Autre')], max_length=50, verbose_name="Type d'infrastructure")),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'infrastructure")),
                ('description', models.TextField(blank=True)),
                ('capacite', models.PositiveIntegerField(blank=True, help_text="Capacité d'accueil (élèves, patients, etc.)", null=True)),
                ('date_construction', models.DateField(blank=True, null=True, verbose_name='Date de construction')),
                ('etat', models.CharField(choices=[('bon', 'Bon état'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état'), ('en_construction', 'En construction'), ('abandonne', 'Abandonné')], default='bon', max_length=20, verbose_name="État de l'infrastructure")),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('contact_responsable', models.CharField(blank=True, max_length=20, verbose_name='Contact du responsable')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='villages.village')),
            ],
            options={
                'verbose_name': 'Infrastructure',
                'verbose_name_plural': 'Infrastructures',
                'ordering': ['village', 'type_infrastructure', 'nom'],
            },
        ),
    ]
